### ISSUE TITLE
Ability to calculate diffs between files/texts

### ISSUE THREAD

**Issue by tameeshB** [chriskuehl/fluffy#134]
Can we add a feature where, we would be able to calculate the diff between two files or texts?
Maybe how this could work is by adding a button "Want to calculate a diff?" which shows a second textarea/file dropbox.
Upon submitting the files/texts, we get a diff of the two inputs on the next page?

**Comment by chriskuehl** [comment]
I wonder if this is the right tool to implement this in. I can see why it would be useful to have but it would IMO probably fit better if we supported revisions of pastes that could be diffed between (see for example how gist does it: https://gist.github.com/chriskuehl/6795bf373861a7f6368ad04cc7ecce8e/revisions). That would definitely be a useful feature (it could pretty easily replace the "Copy & Edit" button we already have) but I think diffing alone strikes me as a strange fit for fluffy.

Do you have a scenario in mind for where this would be useful (like some workflow that would benefit from this)?

**Comment by chriskuehl** [comment]
Merged in #158!
