### ISSUE TITLE
normalize .html and .txt urls

### ISSUE THREAD

**Issue by magicmark** [chriskuehl/fluffy#176]
for big json dumps, loading the page can take forever and crash the browser, and i usually just want to curl it anyway

but if folks provide me the .html page, i can't easily map to the .txt url

could they share the same id in the url?

**Comment by magicmark** [comment]
i see the comment from here https://github.com/chriskuehl/fluffy/issues/62#issuecomment-367505197 which makes sense, but somewhere in `def upload():` can we generate an id and share it with the plaintext and html file in s3?

**Comment by magicmark** [comment]
heck yeah!

<img width="697" alt="Screenshot 2024-08-20 at 4 11 46 PM" src="https://github.com/user-attachments/assets/469edcd4-e8e1-451a-98ce-b809950f0644">

so 'direct link' and 'view text' would be the same url, apart from the suffix

**Comment by chriskuehl** [comment]
I think https://github.com/chriskuehl/fluffy/pull/177 will do it. I'm traveling at the moment but I'll test this more thoroughly and merge it soon.

**Comment by chriskuehl** [comment]
Released in v1.40.0.

Here's an example on the new version: https://i.fluffy.cc/pLRkPrVHQdjqXg5697pwcncxs3VG9Bkv.html
