### ISSUE TITLE
Main link on http://fluffy.cc/ points to localhost:5000

### ISSUE THREAD

**Issue by magicmark** [chriskuehl/fluffy#21]
Clicking big 'fluffy' on http://fluffy.cc/ links to localhost:5000, not prod url

**Comment by chriskuehl** [comment]
Haha thanks! I actually fixed this a few weeks ago but haven't deployed to fluffy.cc (internal fluffy is up-to-date, though). Will do that now!

**Comment by chriskuehl** [comment]
fixed!
