### ISSUE TITLE
Keyboard shortcuts (Cmd-C, ...) don't work on OS X on paste view

### ISSUE THREAD

**Issue by chriskuehl** [chriskuehl/fluffy#27]
@bwbaugh reports that he can't use shortcuts like Cmd-C in the paste view page on Chrome OS X (it works for me on both FF + Chrome on Linux).

**Comment by bwbaugh** [comment]
Renaming the `contenteditable` attribute to something else (like `contenteditable2`) fixes the issue. FWIW, the content isn't editable for me either. However, the [contenteditable demo](http://www.w3schools.com/tags/att_global_contenteditable.asp) works fine for me.

**Comment by chriskuehl** [comment]
It also seems to block keyboard shortcuts like cmd+L (to go to URL bar). not cool!

**Comment by chriskuehl** [comment]
@bwbaugh I released what I believe is a fix in v1.16.1 and deployed it to the public instance (fluffy.cc).

Could you try this link and let me know if it's working properly for you? https://i.fluffy.cc/7M01174wlFJCPvP1QdGczCzGddmSBBmG.html

**Comment by bwbaugh** [comment]
@chriskuehl works! The copy-shortcut now works for me. ❤️
FWIW, I get the blinking cursor as if I was able to edit the text, but it doesn't edit. That's perfectly fine for me, but just wanted to report the behavior.

Thank you for picking this up so fast!

**Comment by chriskuehl** [comment]
Cool, thanks for checking! The blinking cursor is sort of expected but agreed it's a little weird. The goal was so that you can just click into the text area, hit Ctrl-A to select all, and Ctrl-C to copy (or even use shift + arrow keys to select).

So it's weird that it looks somewhat editable, but I think overall it's worth it since it's quite a bit easier to copy text from.
