### ISSUE TITLE
Diff highlights don't work with horizontal scrolling

### ISSUE THREAD

**Issue by chriskuehl** [chriskuehl/fluffy#35]
e.g. https://i.fluffy.cc/v1JrxknC65TGMQB4hFcTQhBtsmDm1t1W.html

![](https://i.fluffy.cc/xGCTW7ctQ3RX7lxFfnbMCKmRwGWSk1ZS.png)

cc @jvperrin

**Comment by jvperrin** [comment]
Yeah, I tried fixing this by making the whole line a block instead, but then I had problems with spacing. I'll try and look into it more, because it would be nice to have full-line highlighting.

**Comment by chriskuehl** [comment]
@drolando noticed you can make the spans `display: inline-block` which fixes it but has the side effect of not having the highlight go the full width (it is only as long as the line).

That's probably an okay solution, but I think (?) I prefer them going all the way? I'm not totally sure.
