### ISSUE TITLE
fpb/fput should have an option to go directly to the raw file

### ISSUE THREAD

**Issue by chriskuehl** [chriskuehl/fluffy#46]
I'd like to use something like `fput --raw <somefile>` and have it give me a link to the file itself. Right now, it can only produce a link to the file details page.

Similarly, `fpb --raw` would produce a link to the plaintext version. Annoyingly, `fpb -r` already exists, maybe we can find a better name than `raw`?

Ideally we'd probably add support to the server for this, since there's no point in uploading multiple views (e.g. file details, pastebin view) when only providing the raw link, as nobody will ever be able to find them.

**Comment by chriskuehl** [comment]
The JSON upload now returns data on individual files and a `raw` link that can be used for this.

**Comment by danielpops** [comment]
How about `--direct-link`?

**Comment by chriskuehl** [comment]
@danielpops good idea, I like that name. Went with that in #71.
