### ISSUE TITLE
Support pasting rich text into web UI

### ISSUE THREAD

**Issue by chriskuehl** [chriskuehl/fluffy#59]
It would be neat if you could paste rich text into the web UI and have the resulting paste keep the formatting.

Would need to somehow balance this against the "annoying" behavior that rich text paste can sometimes have (e.g. you copy from somewhere, but you don't necessarily want to keep the weird font it's using).

**Comment by chriskuehl** [comment]
I think at one point I had a compelling use-case for this, but I can't think of it anymore.

**Comment by lizjakubowski** [comment]
@chriskuehl fwiw, this would be nice to have (maybe toggleable via a checkbox?) for pasting terminal output when there are colorful errors and warnings, to make it easier on the reader 🙂

and ++, I could definitely live without preserving the fonts!
